Add support for S3 Stage
PostHog/snowflake-export-plugin pull request #5
Opened 2021-07-05 15:03 UTC by yakkomajuri

I originally forked #4 but turns out there wasn't too much to reuse from there.

Will add GCS in another PR.

## How this works

- `exportEvents` function sends the events to S3. This is done in CSV format, because Snowflake does not support multi-column JSON inserts. As this is in `exportEvents`, anything that fails here will be retried according to our exponential backoff mechanism.
- `runEveryMinute` is used to actually run every _hour_. This approach is used in other plugins to give immediate feedback on installation. This will issue a `COPY INTO` statement to Snowflake to copy the relevant files from S3. The user can choose if they want to purge these from the stage on copy or not.
- The above will also be retried with exponential backoff, so that we try up to 15 times to send to S3, and yet another 15 to send to Snowflake. This makes sure users get their events for sure.

2021-07-06 12:27 UTC, Twixes commented
Hmm, I get this error when the plugin tries to ingest events from the stage into the table:
<img width="1198" alt="Screen Shot 2021-07-06 at 14 25 56" src="https://user-images.githubusercontent.com/4550621/124599658-33adf100-de66-11eb-8b00-b813b6c7fc7a.png">
Maybe a warehouse should be specified in plugin config too, and `USE`d? Dunno

2021-07-06 12:29 UTC, Twixes commented
Also looks like we should be uppercasing all of stage name, table name, DB name etc. as before the warehouse problem above this was telling me my stage doesn't exist – it was created, but since Snowflake loves uppercase, I also had to uppercase the stage's name in plugin config to fix.

2021-07-06 12:30 UTC, yakkomajuri commented
From the updated README in this PR:

> 2. Make sure you have a [Snowflake Warehouse](https://docs.snowflake.com/en/user-guide/warehouses-overview.html) set up. Warehouses are needed to perform `COPY INTO` statements. We recommend a warehouse that will start up automatically when needed.

I have one on the instance I made available for you, but maybe you don't have permissions for that. Try creating an auto-resume warehouse and this will work. There's no need to actually specify and use it

2021-07-06 12:30 UTC, yakkomajuri commented
The one config option that might make sense is to specify the role to use for a user with many. You have `PUBLIC` and `SYSADMIN` and your `SYSADMIN` role should have permissions on the warehouse.

2021-07-06 12:49 UTC, Twixes commented
Same thing when specifying role `SYSADMIN` with the new setting :(

2021-07-06 13:53 UTC, yakkomajuri commented
Yeah so for me Snowflake provided a warehouse by default:

<img width="621" alt="Screenshot 2021-07-06 at 10 30 23" src="https://user-images.githubusercontent.com/38760734/124611977-54ffe480-de48-11eb-8df4-8051598a20e5.png">

But indeed `USE WAREHOUSE` was the way. Also upper cased everything

2021-07-09 08:16 UTC, Twixes requested changes
This works! But very unreliably, skipping most events: looks like that is because of `filesStagedForCopy` malfunctioning. Most `COPY INTO` queries look like the one below for me – notice the `FILES ( )` clause without any actual files listed, _despite dumps being uploaded to S3 completely properly_.

Actually we should be using `cache` for this list. Since `runEveryX` is redlocked (every X only a _single_ plugin server instance runs the task), `global` is not appropriate for `filesStagedForCopy`, since each plugin server instance has its own `global`. Redis lists would actually be great for this, though would have to expose that in the plugin server first.

<img width="882" alt="Hmm" src="https://user-images.githubusercontent.com/4550621/125009806-8d303e80-e065-11eb-8b40-d5a0dba506c4.png">

2021-07-09 08:16 UTC, Twixes commented on plugin.json
> +            "name": "Snowflake database schema",
Nit: inconsistent capitalization

2021-07-09 08:16 UTC, Twixes commented on plugin.json
> +            "name": "Purge events from stage after copying?",
Wouldn't not purging cause repeated ingestion of old events (along with new ones)?

2021-07-09 08:16 UTC, Twixes commented on README.md
>  # SnowFlake Export Plugin
Nit: should be "Snowflake" everywhere

2021-07-09 09:09 UTC, Twixes commented on plugin.json
> +            "name": "Snowflake database schema",
Outdated comment, sorry!

2021-07-09 09:10 UTC, Twixes commented on plugin.json
> +            "name": "Purge events from stage after copying?",
Old comment too, obvs not the case

2021-07-09 10:30 UTC, yakkomajuri commented
Ah yes indeed

2021-07-12 17:50 UTC, yakkomajuri commented
Done using Redis lists @Twixes

2021-07-12 18:40 UTC, Twixes approved these changes
Brilliant. This works! 🎉

2021-07-12 18:40 UTC, merged